### ISSUE TITLE
please! remove the vbox-x11 its broken at debian

### ISSUE THREAD

**Issue by mckaygerhard** [nomad-desktop/nxos-base-files#2] opened 2017-08-21 03:38 UTC
i tested the nitrus os to see the nomad desktop.. 

cannot see nothing due seems as i noted at boot (after removing the stupid splash) 

that seems tobe using and detecting the vbox container/machine and set the vbox-x11 xorg module

please remove it! are broken in debian...

**Comment by UriHerrera** [comment] 2017-08-21 17:50
Please send an email to hellow@nxos.org thoroughly describing the problem. Closing this issue as off-topic.

**Closed by UriHerrera** 2017-08-21 17:50 UTC

**Comment by mckaygerhard** [comment] 2017-08-21 18:10
ja ja ja, off topic.. its clarelly you only test your iso in few hardware combination..  i dont care its you "almost use " distribution

**Comment by UriHerrera** [comment] 2017-08-21 20:37
Again, please send an email thoroughly describing the problem to the address above. The issue is off-topic here since this repository has nothing to do with virtualbox or its guest additions.

Also, if English isn't your native language we can communicate in Spanish but then again not here, please send an email.

Locking this thread.
